version: "3.7"
services:
  rabbitmq:
    container_name: rabbitmq_service
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  api:
    container_name: api_service
    depends_on:
      - mysql
    restart: on-failure
    build: ./api/
    environment:
      MYSQL_URL: mysql
      PORT: 5000
      DB_USER: user
      DB_PASSWORD: root
    ports:
      - 5000:5000
  film-collector:
    depends_on:
      - mysql
    container_name: film-collector_service
    build: ./film-collector/
    restart: on-failure
    environment:
      MYSQL_URL: mysql
      DB_USER: user
      DB_PASSWORD: root
  mysql:
    container_name: mysql_service
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
  rabbitmq:
