version: "3.7"
services:
  mysql:
    container_name: mysql_service
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
  api:
    container_name: api_service
    depends_on:
      - mysql
    restart: on-failure
    build: ./api/
    environment:
      MYSQL_URL: mysql
      PORT: 5000
      DB_USER: user
      DB_PASSWORD: root
    ports:
      - 5000:5000
